### ISSUE TITLE
Wrong, partial s3 bucket in cloudfront

### ISSUE THREAD

**Issue by jonthewayne** [serverless-components/website#50]
On the most recent Serverless version, had this S3 bucket name as an input:

`bucketName: welcome-dev.remember.us`

The correct s3 bucket is created:

`http://welcome-dev.remember.us.s3-website-us-west-2.amazonaws.com`

I also mapped a subdomain, and it points to a cloudfront dist that was also created.

The problem is that the cloudfront dist has the origin as `welcome-dev.s3.amazonaws.com` which is wrong. It's not using the whole `welcome-dev.remember.us`.

**Comment by eahefnawy** [comment]
hmm that's def a bug. Thanks for reporting. I'll look into it 😊

**Comment by eahefnawy** [comment]
@jonthewayne this should now be resolved. Could you try it again on your end?

**Comment by faradayfan** [comment]
I am seeing this behavior as well. We have updated to serverless version 2.6.0 and it still happens.
